// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: OpenCue/proto/service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Threadable        bool     `protobuf:"varint,3,opt,name=threadable,proto3" json:"threadable,omitempty"`
	MinCores          int32    `protobuf:"varint,4,opt,name=min_cores,json=minCores,proto3" json:"min_cores,omitempty"`
	MaxCores          int32    `protobuf:"varint,5,opt,name=max_cores,json=maxCores,proto3" json:"max_cores,omitempty"`
	MinMemory         int64    `protobuf:"varint,6,opt,name=min_memory,json=minMemory,proto3" json:"min_memory,omitempty"`
	MinGpuMemory      int64    `protobuf:"varint,7,opt,name=min_gpu_memory,json=minGpuMemory,proto3" json:"min_gpu_memory,omitempty"`
	Tags              []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Timeout           int32    `protobuf:"varint,9,opt,name=timeout,proto3" json:"timeout,omitempty"`
	TimeoutLlu        int32    `protobuf:"varint,10,opt,name=timeout_llu,json=timeoutLlu,proto3" json:"timeout_llu,omitempty"`
	MinGpus           int32    `protobuf:"varint,11,opt,name=min_gpus,json=minGpus,proto3" json:"min_gpus,omitempty"`
	MaxGpus           int32    `protobuf:"varint,12,opt,name=max_gpus,json=maxGpus,proto3" json:"max_gpus,omitempty"`
	MinMemoryIncrease int32    `protobuf:"varint,13,opt,name=min_memory_increase,json=minMemoryIncrease,proto3" json:"min_memory_increase,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetThreadable() bool {
	if x != nil {
		return x.Threadable
	}
	return false
}

func (x *Service) GetMinCores() int32 {
	if x != nil {
		return x.MinCores
	}
	return 0
}

func (x *Service) GetMaxCores() int32 {
	if x != nil {
		return x.MaxCores
	}
	return 0
}

func (x *Service) GetMinMemory() int64 {
	if x != nil {
		return x.MinMemory
	}
	return 0
}

func (x *Service) GetMinGpuMemory() int64 {
	if x != nil {
		return x.MinGpuMemory
	}
	return 0
}

func (x *Service) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Service) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Service) GetTimeoutLlu() int32 {
	if x != nil {
		return x.TimeoutLlu
	}
	return 0
}

func (x *Service) GetMinGpus() int32 {
	if x != nil {
		return x.MinGpus
	}
	return 0
}

func (x *Service) GetMaxGpus() int32 {
	if x != nil {
		return x.MaxGpus
	}
	return 0
}

func (x *Service) GetMinMemoryIncrease() int32 {
	if x != nil {
		return x.MinMemoryIncrease
	}
	return 0
}

type ServiceSeq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *ServiceSeq) Reset() {
	*x = ServiceSeq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceSeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSeq) ProtoMessage() {}

func (x *ServiceSeq) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSeq.ProtoReflect.Descriptor instead.
func (*ServiceSeq) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceSeq) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceOverride struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data *Service `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceOverride) Reset() {
	*x = ServiceOverride{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOverride) ProtoMessage() {}

func (x *ServiceOverride) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOverride.ProtoReflect.Descriptor instead.
func (*ServiceOverride) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceOverride) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceOverride) GetData() *Service {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceOverrideSeq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceOverrides []*ServiceOverride `protobuf:"bytes,1,rep,name=service_overrides,json=serviceOverrides,proto3" json:"service_overrides,omitempty"`
}

func (x *ServiceOverrideSeq) Reset() {
	*x = ServiceOverrideSeq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceOverrideSeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOverrideSeq) ProtoMessage() {}

func (x *ServiceOverrideSeq) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOverrideSeq.ProtoReflect.Descriptor instead.
func (*ServiceOverrideSeq) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceOverrideSeq) GetServiceOverrides() []*ServiceOverride {
	if x != nil {
		return x.ServiceOverrides
	}
	return nil
}

// SERVICE ----
// CreateService
type ServiceCreateServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Service `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceCreateServiceRequest) Reset() {
	*x = ServiceCreateServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceCreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCreateServiceRequest) ProtoMessage() {}

func (x *ServiceCreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCreateServiceRequest.ProtoReflect.Descriptor instead.
func (*ServiceCreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceCreateServiceRequest) GetData() *Service {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceCreateServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *ServiceCreateServiceResponse) Reset() {
	*x = ServiceCreateServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceCreateServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCreateServiceResponse) ProtoMessage() {}

func (x *ServiceCreateServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCreateServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceCreateServiceResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceCreateServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

// Delete
type ServiceDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *ServiceDeleteRequest) Reset() {
	*x = ServiceDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDeleteRequest) ProtoMessage() {}

func (x *ServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceDeleteRequest) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type ServiceDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServiceDeleteResponse) Reset() {
	*x = ServiceDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDeleteResponse) ProtoMessage() {}

func (x *ServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*ServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{7}
}

// GetDefaultServices
type ServiceGetDefaultServicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServiceGetDefaultServicesRequest) Reset() {
	*x = ServiceGetDefaultServicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetDefaultServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetDefaultServicesRequest) ProtoMessage() {}

func (x *ServiceGetDefaultServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetDefaultServicesRequest.ProtoReflect.Descriptor instead.
func (*ServiceGetDefaultServicesRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{8}
}

type ServiceGetDefaultServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services *ServiceSeq `protobuf:"bytes,1,opt,name=services,proto3" json:"services,omitempty"`
}

func (x *ServiceGetDefaultServicesResponse) Reset() {
	*x = ServiceGetDefaultServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetDefaultServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetDefaultServicesResponse) ProtoMessage() {}

func (x *ServiceGetDefaultServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetDefaultServicesResponse.ProtoReflect.Descriptor instead.
func (*ServiceGetDefaultServicesResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceGetDefaultServicesResponse) GetServices() *ServiceSeq {
	if x != nil {
		return x.Services
	}
	return nil
}

// GetService
type ServiceGetServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServiceGetServiceRequest) Reset() {
	*x = ServiceGetServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetServiceRequest) ProtoMessage() {}

func (x *ServiceGetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetServiceRequest.ProtoReflect.Descriptor instead.
func (*ServiceGetServiceRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceGetServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ServiceGetServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *ServiceGetServiceResponse) Reset() {
	*x = ServiceGetServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetServiceResponse) ProtoMessage() {}

func (x *ServiceGetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceGetServiceResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceGetServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

// Update
type ServiceUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *ServiceUpdateRequest) Reset() {
	*x = ServiceUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUpdateRequest) ProtoMessage() {}

func (x *ServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *ServiceUpdateRequest) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type ServiceUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServiceUpdateResponse) Reset() {
	*x = ServiceUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUpdateResponse) ProtoMessage() {}

func (x *ServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*ServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{13}
}

// SERVICE OVERRIDE ----
// Delete
type ServiceOverrideDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *ServiceOverrideDeleteRequest) Reset() {
	*x = ServiceOverrideDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceOverrideDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOverrideDeleteRequest) ProtoMessage() {}

func (x *ServiceOverrideDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOverrideDeleteRequest.ProtoReflect.Descriptor instead.
func (*ServiceOverrideDeleteRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{14}
}

func (x *ServiceOverrideDeleteRequest) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type ServiceOverrideDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServiceOverrideDeleteResponse) Reset() {
	*x = ServiceOverrideDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceOverrideDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOverrideDeleteResponse) ProtoMessage() {}

func (x *ServiceOverrideDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOverrideDeleteResponse.ProtoReflect.Descriptor instead.
func (*ServiceOverrideDeleteResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{15}
}

// Update
type ServiceOverrideUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *ServiceOverrideUpdateRequest) Reset() {
	*x = ServiceOverrideUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceOverrideUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOverrideUpdateRequest) ProtoMessage() {}

func (x *ServiceOverrideUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOverrideUpdateRequest.ProtoReflect.Descriptor instead.
func (*ServiceOverrideUpdateRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{16}
}

func (x *ServiceOverrideUpdateRequest) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type ServiceOverrideUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServiceOverrideUpdateResponse) Reset() {
	*x = ServiceOverrideUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceOverrideUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOverrideUpdateResponse) ProtoMessage() {}

func (x *ServiceOverrideUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOverrideUpdateResponse.ProtoReflect.Descriptor instead.
func (*ServiceOverrideUpdateResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_service_proto_rawDescGZIP(), []int{17}
}

var File_OpenCue_proto_service_proto protoreflect.FileDescriptor

var file_OpenCue_proto_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x75, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x81, 0x03, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x74, 0x68, 0x72, 0x65,
	0x61, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x43, 0x6f,
	0x72, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x72, 0x65, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12,
	0x24, 0x0a, 0x0e, 0x6d, 0x69, 0x6e, 0x5f, 0x67, 0x70, 0x75, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x47, 0x70, 0x75, 0x4d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6c,
	0x6c, 0x75, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x4c, 0x6c, 0x75, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x5f, 0x67, 0x70, 0x75, 0x73,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x47, 0x70, 0x75, 0x73, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x67, 0x70, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x47, 0x70, 0x75, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x6d, 0x69,
	0x6e, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73,
	0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x22, 0x3a, 0x0a, 0x0a, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x5b, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69,
	0x64, 0x65, 0x53, 0x65, 0x71, 0x12, 0x45, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x73, 0x22, 0x43, 0x0a, 0x1b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x4a, 0x0a, 0x1c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x42, 0x0a,
	0x14, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x20, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54,
	0x0a, 0x21, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x71, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x22, 0x2e, 0x0a, 0x18, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x19, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x42, 0x0a,
	0x14, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4a, 0x0a, 0x1c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4a, 0x0a, 0x1c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x76,
	0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc4, 0x03, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x24, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x6b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x29, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xcc, 0x01, 0x0a, 0x18,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72,
	0x69, 0x64, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x57, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x76, 0x65,
	0x72, 0x72, 0x69, 0x64, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x0a, 0x21, 0x63, 0x6f,
	0x6d, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x73, 0x70, 0x63,
	0x75, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50,
	0x01, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_OpenCue_proto_service_proto_rawDescOnce sync.Once
	file_OpenCue_proto_service_proto_rawDescData = file_OpenCue_proto_service_proto_rawDesc
)

func file_OpenCue_proto_service_proto_rawDescGZIP() []byte {
	file_OpenCue_proto_service_proto_rawDescOnce.Do(func() {
		file_OpenCue_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_OpenCue_proto_service_proto_rawDescData)
	})
	return file_OpenCue_proto_service_proto_rawDescData
}

var file_OpenCue_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_OpenCue_proto_service_proto_goTypes = []interface{}{
	(*Service)(nil),                           // 0: service.Service
	(*ServiceSeq)(nil),                        // 1: service.ServiceSeq
	(*ServiceOverride)(nil),                   // 2: service.ServiceOverride
	(*ServiceOverrideSeq)(nil),                // 3: service.ServiceOverrideSeq
	(*ServiceCreateServiceRequest)(nil),       // 4: service.ServiceCreateServiceRequest
	(*ServiceCreateServiceResponse)(nil),      // 5: service.ServiceCreateServiceResponse
	(*ServiceDeleteRequest)(nil),              // 6: service.ServiceDeleteRequest
	(*ServiceDeleteResponse)(nil),             // 7: service.ServiceDeleteResponse
	(*ServiceGetDefaultServicesRequest)(nil),  // 8: service.ServiceGetDefaultServicesRequest
	(*ServiceGetDefaultServicesResponse)(nil), // 9: service.ServiceGetDefaultServicesResponse
	(*ServiceGetServiceRequest)(nil),          // 10: service.ServiceGetServiceRequest
	(*ServiceGetServiceResponse)(nil),         // 11: service.ServiceGetServiceResponse
	(*ServiceUpdateRequest)(nil),              // 12: service.ServiceUpdateRequest
	(*ServiceUpdateResponse)(nil),             // 13: service.ServiceUpdateResponse
	(*ServiceOverrideDeleteRequest)(nil),      // 14: service.ServiceOverrideDeleteRequest
	(*ServiceOverrideDeleteResponse)(nil),     // 15: service.ServiceOverrideDeleteResponse
	(*ServiceOverrideUpdateRequest)(nil),      // 16: service.ServiceOverrideUpdateRequest
	(*ServiceOverrideUpdateResponse)(nil),     // 17: service.ServiceOverrideUpdateResponse
}
var file_OpenCue_proto_service_proto_depIdxs = []int32{
	0,  // 0: service.ServiceSeq.services:type_name -> service.Service
	0,  // 1: service.ServiceOverride.data:type_name -> service.Service
	2,  // 2: service.ServiceOverrideSeq.service_overrides:type_name -> service.ServiceOverride
	0,  // 3: service.ServiceCreateServiceRequest.data:type_name -> service.Service
	0,  // 4: service.ServiceCreateServiceResponse.service:type_name -> service.Service
	0,  // 5: service.ServiceDeleteRequest.service:type_name -> service.Service
	1,  // 6: service.ServiceGetDefaultServicesResponse.services:type_name -> service.ServiceSeq
	0,  // 7: service.ServiceGetServiceResponse.service:type_name -> service.Service
	0,  // 8: service.ServiceUpdateRequest.service:type_name -> service.Service
	0,  // 9: service.ServiceOverrideDeleteRequest.service:type_name -> service.Service
	0,  // 10: service.ServiceOverrideUpdateRequest.service:type_name -> service.Service
	4,  // 11: service.ServiceInterface.CreateService:input_type -> service.ServiceCreateServiceRequest
	6,  // 12: service.ServiceInterface.Delete:input_type -> service.ServiceDeleteRequest
	8,  // 13: service.ServiceInterface.GetDefaultServices:input_type -> service.ServiceGetDefaultServicesRequest
	10, // 14: service.ServiceInterface.GetService:input_type -> service.ServiceGetServiceRequest
	12, // 15: service.ServiceInterface.Update:input_type -> service.ServiceUpdateRequest
	14, // 16: service.ServiceOverrideInterface.Delete:input_type -> service.ServiceOverrideDeleteRequest
	16, // 17: service.ServiceOverrideInterface.Update:input_type -> service.ServiceOverrideUpdateRequest
	5,  // 18: service.ServiceInterface.CreateService:output_type -> service.ServiceCreateServiceResponse
	7,  // 19: service.ServiceInterface.Delete:output_type -> service.ServiceDeleteResponse
	9,  // 20: service.ServiceInterface.GetDefaultServices:output_type -> service.ServiceGetDefaultServicesResponse
	11, // 21: service.ServiceInterface.GetService:output_type -> service.ServiceGetServiceResponse
	13, // 22: service.ServiceInterface.Update:output_type -> service.ServiceUpdateResponse
	15, // 23: service.ServiceOverrideInterface.Delete:output_type -> service.ServiceOverrideDeleteResponse
	17, // 24: service.ServiceOverrideInterface.Update:output_type -> service.ServiceOverrideUpdateResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_OpenCue_proto_service_proto_init() }
func file_OpenCue_proto_service_proto_init() {
	if File_OpenCue_proto_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_OpenCue_proto_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceSeq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceOverride); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceOverrideSeq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceCreateServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceCreateServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetDefaultServicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetDefaultServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceOverrideDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceOverrideDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceOverrideUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceOverrideUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_OpenCue_proto_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_OpenCue_proto_service_proto_goTypes,
		DependencyIndexes: file_OpenCue_proto_service_proto_depIdxs,
		MessageInfos:      file_OpenCue_proto_service_proto_msgTypes,
	}.Build()
	File_OpenCue_proto_service_proto = out.File
	file_OpenCue_proto_service_proto_rawDesc = nil
	file_OpenCue_proto_service_proto_goTypes = nil
	file_OpenCue_proto_service_proto_depIdxs = nil
}
