// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: OpenCue/proto/criterion.proto

package criterion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EqualsFloatSearchCriterion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float32 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EqualsFloatSearchCriterion) Reset() {
	*x = EqualsFloatSearchCriterion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_criterion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EqualsFloatSearchCriterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EqualsFloatSearchCriterion) ProtoMessage() {}

func (x *EqualsFloatSearchCriterion) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_criterion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EqualsFloatSearchCriterion.ProtoReflect.Descriptor instead.
func (*EqualsFloatSearchCriterion) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_criterion_proto_rawDescGZIP(), []int{0}
}

func (x *EqualsFloatSearchCriterion) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type EqualsIntegerSearchCriterion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EqualsIntegerSearchCriterion) Reset() {
	*x = EqualsIntegerSearchCriterion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_criterion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EqualsIntegerSearchCriterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EqualsIntegerSearchCriterion) ProtoMessage() {}

func (x *EqualsIntegerSearchCriterion) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_criterion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EqualsIntegerSearchCriterion.ProtoReflect.Descriptor instead.
func (*EqualsIntegerSearchCriterion) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_criterion_proto_rawDescGZIP(), []int{1}
}

func (x *EqualsIntegerSearchCriterion) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GreaterThanFloatSearchCriterion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float32 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GreaterThanFloatSearchCriterion) Reset() {
	*x = GreaterThanFloatSearchCriterion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_criterion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreaterThanFloatSearchCriterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreaterThanFloatSearchCriterion) ProtoMessage() {}

func (x *GreaterThanFloatSearchCriterion) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_criterion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreaterThanFloatSearchCriterion.ProtoReflect.Descriptor instead.
func (*GreaterThanFloatSearchCriterion) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_criterion_proto_rawDescGZIP(), []int{2}
}

func (x *GreaterThanFloatSearchCriterion) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GreaterThanIntegerSearchCriterion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GreaterThanIntegerSearchCriterion) Reset() {
	*x = GreaterThanIntegerSearchCriterion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_criterion_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreaterThanIntegerSearchCriterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreaterThanIntegerSearchCriterion) ProtoMessage() {}

func (x *GreaterThanIntegerSearchCriterion) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_criterion_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreaterThanIntegerSearchCriterion.ProtoReflect.Descriptor instead.
func (*GreaterThanIntegerSearchCriterion) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_criterion_proto_rawDescGZIP(), []int{3}
}

func (x *GreaterThanIntegerSearchCriterion) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type InRangeFloatSearchCriterion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min float32 `protobuf:"fixed32,1,opt,name=min,proto3" json:"min,omitempty"`
	Max float32 `protobuf:"fixed32,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *InRangeFloatSearchCriterion) Reset() {
	*x = InRangeFloatSearchCriterion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_criterion_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InRangeFloatSearchCriterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InRangeFloatSearchCriterion) ProtoMessage() {}

func (x *InRangeFloatSearchCriterion) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_criterion_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InRangeFloatSearchCriterion.ProtoReflect.Descriptor instead.
func (*InRangeFloatSearchCriterion) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_criterion_proto_rawDescGZIP(), []int{4}
}

func (x *InRangeFloatSearchCriterion) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *InRangeFloatSearchCriterion) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type InRangeIntegerSearchCriterion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min int32 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max int32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *InRangeIntegerSearchCriterion) Reset() {
	*x = InRangeIntegerSearchCriterion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_criterion_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InRangeIntegerSearchCriterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InRangeIntegerSearchCriterion) ProtoMessage() {}

func (x *InRangeIntegerSearchCriterion) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_criterion_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InRangeIntegerSearchCriterion.ProtoReflect.Descriptor instead.
func (*InRangeIntegerSearchCriterion) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_criterion_proto_rawDescGZIP(), []int{5}
}

func (x *InRangeIntegerSearchCriterion) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *InRangeIntegerSearchCriterion) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type LessThanFloatSearchCriterion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float32 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LessThanFloatSearchCriterion) Reset() {
	*x = LessThanFloatSearchCriterion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_criterion_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LessThanFloatSearchCriterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessThanFloatSearchCriterion) ProtoMessage() {}

func (x *LessThanFloatSearchCriterion) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_criterion_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessThanFloatSearchCriterion.ProtoReflect.Descriptor instead.
func (*LessThanFloatSearchCriterion) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_criterion_proto_rawDescGZIP(), []int{6}
}

func (x *LessThanFloatSearchCriterion) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type LessThanIntegerSearchCriterion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LessThanIntegerSearchCriterion) Reset() {
	*x = LessThanIntegerSearchCriterion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_criterion_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LessThanIntegerSearchCriterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessThanIntegerSearchCriterion) ProtoMessage() {}

func (x *LessThanIntegerSearchCriterion) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_criterion_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessThanIntegerSearchCriterion.ProtoReflect.Descriptor instead.
func (*LessThanIntegerSearchCriterion) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_criterion_proto_rawDescGZIP(), []int{7}
}

func (x *LessThanIntegerSearchCriterion) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_OpenCue_proto_criterion_proto protoreflect.FileDescriptor

var file_OpenCue_proto_criterion_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x75, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x63, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x22, 0x32, 0x0a, 0x1a, 0x45, 0x71,
	0x75, 0x61, 0x6c, 0x73, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x34,
	0x0a, 0x1c, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x1f, 0x47, 0x72, 0x65, 0x61, 0x74, 0x65, 0x72, 0x54,
	0x68, 0x61, 0x6e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x39, 0x0a,
	0x21, 0x47, 0x72, 0x65, 0x61, 0x74, 0x65, 0x72, 0x54, 0x68, 0x61, 0x6e, 0x49, 0x6e, 0x74, 0x65,
	0x67, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x41, 0x0a, 0x1b, 0x49, 0x6e, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x43, 0x0a, 0x1d, 0x49,
	0x6e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x61, 0x78,
	0x22, 0x34, 0x0a, 0x1c, 0x4c, 0x65, 0x73, 0x73, 0x54, 0x68, 0x61, 0x6e, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x36, 0x0a, 0x1e, 0x4c, 0x65, 0x73, 0x73, 0x54, 0x68,
	0x61, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x38,
	0x0a, 0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x2e, 0x73, 0x70, 0x63, 0x75, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x72, 0x69, 0x74,
	0x65, 0x72, 0x69, 0x6f, 0x6e, 0x50, 0x01, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_OpenCue_proto_criterion_proto_rawDescOnce sync.Once
	file_OpenCue_proto_criterion_proto_rawDescData = file_OpenCue_proto_criterion_proto_rawDesc
)

func file_OpenCue_proto_criterion_proto_rawDescGZIP() []byte {
	file_OpenCue_proto_criterion_proto_rawDescOnce.Do(func() {
		file_OpenCue_proto_criterion_proto_rawDescData = protoimpl.X.CompressGZIP(file_OpenCue_proto_criterion_proto_rawDescData)
	})
	return file_OpenCue_proto_criterion_proto_rawDescData
}

var file_OpenCue_proto_criterion_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_OpenCue_proto_criterion_proto_goTypes = []interface{}{
	(*EqualsFloatSearchCriterion)(nil),        // 0: criterion.EqualsFloatSearchCriterion
	(*EqualsIntegerSearchCriterion)(nil),      // 1: criterion.EqualsIntegerSearchCriterion
	(*GreaterThanFloatSearchCriterion)(nil),   // 2: criterion.GreaterThanFloatSearchCriterion
	(*GreaterThanIntegerSearchCriterion)(nil), // 3: criterion.GreaterThanIntegerSearchCriterion
	(*InRangeFloatSearchCriterion)(nil),       // 4: criterion.InRangeFloatSearchCriterion
	(*InRangeIntegerSearchCriterion)(nil),     // 5: criterion.InRangeIntegerSearchCriterion
	(*LessThanFloatSearchCriterion)(nil),      // 6: criterion.LessThanFloatSearchCriterion
	(*LessThanIntegerSearchCriterion)(nil),    // 7: criterion.LessThanIntegerSearchCriterion
}
var file_OpenCue_proto_criterion_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_OpenCue_proto_criterion_proto_init() }
func file_OpenCue_proto_criterion_proto_init() {
	if File_OpenCue_proto_criterion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_OpenCue_proto_criterion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EqualsFloatSearchCriterion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_criterion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EqualsIntegerSearchCriterion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_criterion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreaterThanFloatSearchCriterion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_criterion_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreaterThanIntegerSearchCriterion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_criterion_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InRangeFloatSearchCriterion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_criterion_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InRangeIntegerSearchCriterion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_criterion_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LessThanFloatSearchCriterion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_criterion_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LessThanIntegerSearchCriterion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_OpenCue_proto_criterion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OpenCue_proto_criterion_proto_goTypes,
		DependencyIndexes: file_OpenCue_proto_criterion_proto_depIdxs,
		MessageInfos:      file_OpenCue_proto_criterion_proto_msgTypes,
	}.Build()
	File_OpenCue_proto_criterion_proto = out.File
	file_OpenCue_proto_criterion_proto_rawDesc = nil
	file_OpenCue_proto_criterion_proto_goTypes = nil
	file_OpenCue_proto_criterion_proto_depIdxs = nil
}
