// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: OpenCue/proto/task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Shot        string  `protobuf:"bytes,3,opt,name=shot,proto3" json:"shot,omitempty"`
	Dept        string  `protobuf:"bytes,4,opt,name=dept,proto3" json:"dept,omitempty"`
	PointId     string  `protobuf:"bytes,5,opt,name=point_id,json=pointId,proto3" json:"point_id,omitempty"`
	MinCores    float32 `protobuf:"fixed32,6,opt,name=min_cores,json=minCores,proto3" json:"min_cores,omitempty"`
	AdjustCores float32 `protobuf:"fixed32,7,opt,name=adjust_cores,json=adjustCores,proto3" json:"adjust_cores,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetShot() string {
	if x != nil {
		return x.Shot
	}
	return ""
}

func (x *Task) GetDept() string {
	if x != nil {
		return x.Dept
	}
	return ""
}

func (x *Task) GetPointId() string {
	if x != nil {
		return x.PointId
	}
	return ""
}

func (x *Task) GetMinCores() float32 {
	if x != nil {
		return x.MinCores
	}
	return 0
}

func (x *Task) GetAdjustCores() float32 {
	if x != nil {
		return x.AdjustCores
	}
	return 0
}

type TaskSeq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *TaskSeq) Reset() {
	*x = TaskSeq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_task_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskSeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSeq) ProtoMessage() {}

func (x *TaskSeq) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_task_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSeq.ProtoReflect.Descriptor instead.
func (*TaskSeq) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskSeq) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// ClearAdjustments
type TaskClearAdjustmentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *TaskClearAdjustmentsRequest) Reset() {
	*x = TaskClearAdjustmentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_task_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskClearAdjustmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskClearAdjustmentsRequest) ProtoMessage() {}

func (x *TaskClearAdjustmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_task_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskClearAdjustmentsRequest.ProtoReflect.Descriptor instead.
func (*TaskClearAdjustmentsRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskClearAdjustmentsRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type TaskClearAdjustmentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskClearAdjustmentsResponse) Reset() {
	*x = TaskClearAdjustmentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_task_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskClearAdjustmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskClearAdjustmentsResponse) ProtoMessage() {}

func (x *TaskClearAdjustmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_task_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskClearAdjustmentsResponse.ProtoReflect.Descriptor instead.
func (*TaskClearAdjustmentsResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_task_proto_rawDescGZIP(), []int{3}
}

// Delete
type TaskDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *TaskDeleteRequest) Reset() {
	*x = TaskDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_task_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDeleteRequest) ProtoMessage() {}

func (x *TaskDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_task_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDeleteRequest.ProtoReflect.Descriptor instead.
func (*TaskDeleteRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_task_proto_rawDescGZIP(), []int{4}
}

func (x *TaskDeleteRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type TaskDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskDeleteResponse) Reset() {
	*x = TaskDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_task_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDeleteResponse) ProtoMessage() {}

func (x *TaskDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_task_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDeleteResponse.ProtoReflect.Descriptor instead.
func (*TaskDeleteResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_task_proto_rawDescGZIP(), []int{5}
}

// SetMinCores
type TaskSetMinCoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task        *Task   `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	NewMinCores float32 `protobuf:"fixed32,2,opt,name=new_min_cores,json=newMinCores,proto3" json:"new_min_cores,omitempty"`
}

func (x *TaskSetMinCoresRequest) Reset() {
	*x = TaskSetMinCoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_task_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskSetMinCoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSetMinCoresRequest) ProtoMessage() {}

func (x *TaskSetMinCoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_task_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSetMinCoresRequest.ProtoReflect.Descriptor instead.
func (*TaskSetMinCoresRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_task_proto_rawDescGZIP(), []int{6}
}

func (x *TaskSetMinCoresRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *TaskSetMinCoresRequest) GetNewMinCores() float32 {
	if x != nil {
		return x.NewMinCores
	}
	return 0
}

type TaskSetMinCoresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskSetMinCoresResponse) Reset() {
	*x = TaskSetMinCoresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_task_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskSetMinCoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSetMinCoresResponse) ProtoMessage() {}

func (x *TaskSetMinCoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_task_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSetMinCoresResponse.ProtoReflect.Descriptor instead.
func (*TaskSetMinCoresResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_task_proto_rawDescGZIP(), []int{7}
}

var File_OpenCue_proto_task_proto protoreflect.FileDescriptor

var file_OpenCue_proto_task_proto_rawDesc = []byte{
	0x0a, 0x18, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x75, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x61, 0x73, 0x6b,
	0x22, 0xad, 0x01, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x68, 0x6f,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x65, 0x70, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0b, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x43, 0x6f, 0x72, 0x65, 0x73,
	0x22, 0x2b, 0x0a, 0x07, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x05, 0x74,
	0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x61, 0x73,
	0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x3d, 0x0a,
	0x1b, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04,
	0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x61, 0x73,
	0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x1e, 0x0a, 0x1c,
	0x54, 0x61, 0x73, 0x6b, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x33, 0x0a, 0x11,
	0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73,
	0x6b, 0x22, 0x14, 0x0a, 0x12, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5c, 0x0a, 0x16, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x65, 0x74, 0x4d, 0x69, 0x6e, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73,
	0x6b, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x5f, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x72,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x4d, 0x69, 0x6e,
	0x43, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x74,
	0x4d, 0x69, 0x6e, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0xf3, 0x01, 0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x12, 0x59, 0x0a, 0x10, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x64, 0x6a, 0x75, 0x73,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x21, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
	0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x53, 0x65,
	0x74, 0x4d, 0x69, 0x6e, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x43, 0x6f, 0x72, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x53, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x73, 0x70, 0x63, 0x75, 0x65, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x50, 0x01, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_OpenCue_proto_task_proto_rawDescOnce sync.Once
	file_OpenCue_proto_task_proto_rawDescData = file_OpenCue_proto_task_proto_rawDesc
)

func file_OpenCue_proto_task_proto_rawDescGZIP() []byte {
	file_OpenCue_proto_task_proto_rawDescOnce.Do(func() {
		file_OpenCue_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(file_OpenCue_proto_task_proto_rawDescData)
	})
	return file_OpenCue_proto_task_proto_rawDescData
}

var file_OpenCue_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_OpenCue_proto_task_proto_goTypes = []interface{}{
	(*Task)(nil),                         // 0: task.Task
	(*TaskSeq)(nil),                      // 1: task.TaskSeq
	(*TaskClearAdjustmentsRequest)(nil),  // 2: task.TaskClearAdjustmentsRequest
	(*TaskClearAdjustmentsResponse)(nil), // 3: task.TaskClearAdjustmentsResponse
	(*TaskDeleteRequest)(nil),            // 4: task.TaskDeleteRequest
	(*TaskDeleteResponse)(nil),           // 5: task.TaskDeleteResponse
	(*TaskSetMinCoresRequest)(nil),       // 6: task.TaskSetMinCoresRequest
	(*TaskSetMinCoresResponse)(nil),      // 7: task.TaskSetMinCoresResponse
}
var file_OpenCue_proto_task_proto_depIdxs = []int32{
	0, // 0: task.TaskSeq.tasks:type_name -> task.Task
	0, // 1: task.TaskClearAdjustmentsRequest.task:type_name -> task.Task
	0, // 2: task.TaskDeleteRequest.task:type_name -> task.Task
	0, // 3: task.TaskSetMinCoresRequest.task:type_name -> task.Task
	2, // 4: task.TaskInterface.ClearAdjustments:input_type -> task.TaskClearAdjustmentsRequest
	4, // 5: task.TaskInterface.Delete:input_type -> task.TaskDeleteRequest
	6, // 6: task.TaskInterface.SetMinCores:input_type -> task.TaskSetMinCoresRequest
	3, // 7: task.TaskInterface.ClearAdjustments:output_type -> task.TaskClearAdjustmentsResponse
	5, // 8: task.TaskInterface.Delete:output_type -> task.TaskDeleteResponse
	7, // 9: task.TaskInterface.SetMinCores:output_type -> task.TaskSetMinCoresResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_OpenCue_proto_task_proto_init() }
func file_OpenCue_proto_task_proto_init() {
	if File_OpenCue_proto_task_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_OpenCue_proto_task_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_task_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskSeq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_task_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskClearAdjustmentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_task_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskClearAdjustmentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_task_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_task_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_task_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskSetMinCoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_task_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskSetMinCoresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_OpenCue_proto_task_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_OpenCue_proto_task_proto_goTypes,
		DependencyIndexes: file_OpenCue_proto_task_proto_depIdxs,
		MessageInfos:      file_OpenCue_proto_task_proto_msgTypes,
	}.Build()
	File_OpenCue_proto_task_proto = out.File
	file_OpenCue_proto_task_proto_rawDesc = nil
	file_OpenCue_proto_task_proto_goTypes = nil
	file_OpenCue_proto_task_proto_depIdxs = nil
}
