// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: OpenCue/proto/department.proto

package department

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	task "github.com/reski-rukmantiyo/go-pycue/proto/task"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Department struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Dept      string  `protobuf:"bytes,3,opt,name=dept,proto3" json:"dept,omitempty"`
	TiTask    string  `protobuf:"bytes,4,opt,name=ti_task,json=tiTask,proto3" json:"ti_task,omitempty"`
	MinCores  float32 `protobuf:"fixed32,5,opt,name=min_cores,json=minCores,proto3" json:"min_cores,omitempty"`
	TiManaged bool    `protobuf:"varint,6,opt,name=ti_managed,json=tiManaged,proto3" json:"ti_managed,omitempty"`
}

func (x *Department) Reset() {
	*x = Department{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{0}
}

func (x *Department) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Department) GetDept() string {
	if x != nil {
		return x.Dept
	}
	return ""
}

func (x *Department) GetTiTask() string {
	if x != nil {
		return x.TiTask
	}
	return ""
}

func (x *Department) GetMinCores() float32 {
	if x != nil {
		return x.MinCores
	}
	return 0
}

func (x *Department) GetTiManaged() bool {
	if x != nil {
		return x.TiManaged
	}
	return false
}

type DepartmentSeq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Departments []*Department `protobuf:"bytes,1,rep,name=departments,proto3" json:"departments,omitempty"`
}

func (x *DepartmentSeq) Reset() {
	*x = DepartmentSeq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepartmentSeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentSeq) ProtoMessage() {}

func (x *DepartmentSeq) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentSeq.ProtoReflect.Descriptor instead.
func (*DepartmentSeq) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{1}
}

func (x *DepartmentSeq) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

// AddDeptName
type DeptAddDeptNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeptAddDeptNameRequest) Reset() {
	*x = DeptAddDeptNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptAddDeptNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptAddDeptNameRequest) ProtoMessage() {}

func (x *DeptAddDeptNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptAddDeptNameRequest.ProtoReflect.Descriptor instead.
func (*DeptAddDeptNameRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{2}
}

func (x *DeptAddDeptNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeptAddDeptNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeptAddDeptNameResponse) Reset() {
	*x = DeptAddDeptNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptAddDeptNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptAddDeptNameResponse) ProtoMessage() {}

func (x *DeptAddDeptNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptAddDeptNameResponse.ProtoReflect.Descriptor instead.
func (*DeptAddDeptNameResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{3}
}

// AddTask
type DeptAddTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Department *Department `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	Shot       string      `protobuf:"bytes,2,opt,name=shot,proto3" json:"shot,omitempty"`
	MinCores   float32     `protobuf:"fixed32,3,opt,name=min_cores,json=minCores,proto3" json:"min_cores,omitempty"`
}

func (x *DeptAddTaskRequest) Reset() {
	*x = DeptAddTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptAddTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptAddTaskRequest) ProtoMessage() {}

func (x *DeptAddTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptAddTaskRequest.ProtoReflect.Descriptor instead.
func (*DeptAddTaskRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{4}
}

func (x *DeptAddTaskRequest) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

func (x *DeptAddTaskRequest) GetShot() string {
	if x != nil {
		return x.Shot
	}
	return ""
}

func (x *DeptAddTaskRequest) GetMinCores() float32 {
	if x != nil {
		return x.MinCores
	}
	return 0
}

type DeptAddTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *task.Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *DeptAddTaskResponse) Reset() {
	*x = DeptAddTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptAddTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptAddTaskResponse) ProtoMessage() {}

func (x *DeptAddTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptAddTaskResponse.ProtoReflect.Descriptor instead.
func (*DeptAddTaskResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{5}
}

func (x *DeptAddTaskResponse) GetTask() *task.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// AddTasks
type DeptAddTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Department *Department `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	// tmap is a mapping of <(string) shot_id :(int) min_core_units> used to create a task
	Tmap map[string]int32 `protobuf:"bytes,2,rep,name=tmap,proto3" json:"tmap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *DeptAddTasksRequest) Reset() {
	*x = DeptAddTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptAddTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptAddTasksRequest) ProtoMessage() {}

func (x *DeptAddTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptAddTasksRequest.ProtoReflect.Descriptor instead.
func (*DeptAddTasksRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{6}
}

func (x *DeptAddTasksRequest) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

func (x *DeptAddTasksRequest) GetTmap() map[string]int32 {
	if x != nil {
		return x.Tmap
	}
	return nil
}

type DeptAddTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks *task.TaskSeq `protobuf:"bytes,1,opt,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *DeptAddTasksResponse) Reset() {
	*x = DeptAddTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptAddTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptAddTasksResponse) ProtoMessage() {}

func (x *DeptAddTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptAddTasksResponse.ProtoReflect.Descriptor instead.
func (*DeptAddTasksResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{7}
}

func (x *DeptAddTasksResponse) GetTasks() *task.TaskSeq {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// ClearTasks
type DeptClearTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Department *Department `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
}

func (x *DeptClearTasksRequest) Reset() {
	*x = DeptClearTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptClearTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptClearTasksRequest) ProtoMessage() {}

func (x *DeptClearTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptClearTasksRequest.ProtoReflect.Descriptor instead.
func (*DeptClearTasksRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{8}
}

func (x *DeptClearTasksRequest) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type DeptClearTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeptClearTasksResponse) Reset() {
	*x = DeptClearTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptClearTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptClearTasksResponse) ProtoMessage() {}

func (x *DeptClearTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptClearTasksResponse.ProtoReflect.Descriptor instead.
func (*DeptClearTasksResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{9}
}

// ClearTaskAdjustments
type DeptClearTaskAdjustmentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Department *Department `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
}

func (x *DeptClearTaskAdjustmentsRequest) Reset() {
	*x = DeptClearTaskAdjustmentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptClearTaskAdjustmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptClearTaskAdjustmentsRequest) ProtoMessage() {}

func (x *DeptClearTaskAdjustmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptClearTaskAdjustmentsRequest.ProtoReflect.Descriptor instead.
func (*DeptClearTaskAdjustmentsRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{10}
}

func (x *DeptClearTaskAdjustmentsRequest) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type DeptClearTaskAdjustmentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeptClearTaskAdjustmentsResponse) Reset() {
	*x = DeptClearTaskAdjustmentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptClearTaskAdjustmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptClearTaskAdjustmentsResponse) ProtoMessage() {}

func (x *DeptClearTaskAdjustmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptClearTaskAdjustmentsResponse.ProtoReflect.Descriptor instead.
func (*DeptClearTaskAdjustmentsResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{11}
}

// Delete
type DeptDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Department *Department `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
}

func (x *DeptDeleteRequest) Reset() {
	*x = DeptDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptDeleteRequest) ProtoMessage() {}

func (x *DeptDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptDeleteRequest.ProtoReflect.Descriptor instead.
func (*DeptDeleteRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{12}
}

func (x *DeptDeleteRequest) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type DeptDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeptDeleteResponse) Reset() {
	*x = DeptDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptDeleteResponse) ProtoMessage() {}

func (x *DeptDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptDeleteResponse.ProtoReflect.Descriptor instead.
func (*DeptDeleteResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{13}
}

// DisableTiManaged
type DeptDisableTiManagedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Department *Department `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
}

func (x *DeptDisableTiManagedRequest) Reset() {
	*x = DeptDisableTiManagedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptDisableTiManagedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptDisableTiManagedRequest) ProtoMessage() {}

func (x *DeptDisableTiManagedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptDisableTiManagedRequest.ProtoReflect.Descriptor instead.
func (*DeptDisableTiManagedRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{14}
}

func (x *DeptDisableTiManagedRequest) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type DeptDisableTiManagedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeptDisableTiManagedResponse) Reset() {
	*x = DeptDisableTiManagedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptDisableTiManagedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptDisableTiManagedResponse) ProtoMessage() {}

func (x *DeptDisableTiManagedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptDisableTiManagedResponse.ProtoReflect.Descriptor instead.
func (*DeptDisableTiManagedResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{15}
}

// EnableTiManaged
type DeptEnableTiManagedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Department   *Department `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	TiTask       string      `protobuf:"bytes,2,opt,name=ti_task,json=tiTask,proto3" json:"ti_task,omitempty"`
	ManagedCores float32     `protobuf:"fixed32,3,opt,name=managed_cores,json=managedCores,proto3" json:"managed_cores,omitempty"`
}

func (x *DeptEnableTiManagedRequest) Reset() {
	*x = DeptEnableTiManagedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptEnableTiManagedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptEnableTiManagedRequest) ProtoMessage() {}

func (x *DeptEnableTiManagedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptEnableTiManagedRequest.ProtoReflect.Descriptor instead.
func (*DeptEnableTiManagedRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{16}
}

func (x *DeptEnableTiManagedRequest) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

func (x *DeptEnableTiManagedRequest) GetTiTask() string {
	if x != nil {
		return x.TiTask
	}
	return ""
}

func (x *DeptEnableTiManagedRequest) GetManagedCores() float32 {
	if x != nil {
		return x.ManagedCores
	}
	return 0
}

type DeptEnableTiManagedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeptEnableTiManagedResponse) Reset() {
	*x = DeptEnableTiManagedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptEnableTiManagedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptEnableTiManagedResponse) ProtoMessage() {}

func (x *DeptEnableTiManagedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptEnableTiManagedResponse.ProtoReflect.Descriptor instead.
func (*DeptEnableTiManagedResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{17}
}

// GetDepartmentNames
type DeptGetDepartmentNamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeptGetDepartmentNamesRequest) Reset() {
	*x = DeptGetDepartmentNamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptGetDepartmentNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptGetDepartmentNamesRequest) ProtoMessage() {}

func (x *DeptGetDepartmentNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptGetDepartmentNamesRequest.ProtoReflect.Descriptor instead.
func (*DeptGetDepartmentNamesRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{18}
}

type DeptGetDepartmentNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *DeptGetDepartmentNamesResponse) Reset() {
	*x = DeptGetDepartmentNamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptGetDepartmentNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptGetDepartmentNamesResponse) ProtoMessage() {}

func (x *DeptGetDepartmentNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptGetDepartmentNamesResponse.ProtoReflect.Descriptor instead.
func (*DeptGetDepartmentNamesResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{19}
}

func (x *DeptGetDepartmentNamesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// GetTasks
type DeptGetTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Department *Department `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
}

func (x *DeptGetTasksRequest) Reset() {
	*x = DeptGetTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptGetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptGetTasksRequest) ProtoMessage() {}

func (x *DeptGetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptGetTasksRequest.ProtoReflect.Descriptor instead.
func (*DeptGetTasksRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{20}
}

func (x *DeptGetTasksRequest) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type DeptGetTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks *task.TaskSeq `protobuf:"bytes,1,opt,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *DeptGetTasksResponse) Reset() {
	*x = DeptGetTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptGetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptGetTasksResponse) ProtoMessage() {}

func (x *DeptGetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptGetTasksResponse.ProtoReflect.Descriptor instead.
func (*DeptGetTasksResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{21}
}

func (x *DeptGetTasksResponse) GetTasks() *task.TaskSeq {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// RemoveDepartmentName
type DeptRemoveDepartmentNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeptRemoveDepartmentNameRequest) Reset() {
	*x = DeptRemoveDepartmentNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptRemoveDepartmentNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptRemoveDepartmentNameRequest) ProtoMessage() {}

func (x *DeptRemoveDepartmentNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptRemoveDepartmentNameRequest.ProtoReflect.Descriptor instead.
func (*DeptRemoveDepartmentNameRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{22}
}

func (x *DeptRemoveDepartmentNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeptRemoveDepartmentNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeptRemoveDepartmentNameResponse) Reset() {
	*x = DeptRemoveDepartmentNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptRemoveDepartmentNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptRemoveDepartmentNameResponse) ProtoMessage() {}

func (x *DeptRemoveDepartmentNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptRemoveDepartmentNameResponse.ProtoReflect.Descriptor instead.
func (*DeptRemoveDepartmentNameResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{23}
}

// ReplaceTask
type DeptReplaceTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Department *Department `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	// tmap is a mapping of <(string) shot_id :(int) min_core_units> used to create a task
	Tmap map[string]int32 `protobuf:"bytes,2,rep,name=tmap,proto3" json:"tmap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *DeptReplaceTaskRequest) Reset() {
	*x = DeptReplaceTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptReplaceTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptReplaceTaskRequest) ProtoMessage() {}

func (x *DeptReplaceTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptReplaceTaskRequest.ProtoReflect.Descriptor instead.
func (*DeptReplaceTaskRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{24}
}

func (x *DeptReplaceTaskRequest) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

func (x *DeptReplaceTaskRequest) GetTmap() map[string]int32 {
	if x != nil {
		return x.Tmap
	}
	return nil
}

type DeptReplaceTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks *task.TaskSeq `protobuf:"bytes,1,opt,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *DeptReplaceTaskResponse) Reset() {
	*x = DeptReplaceTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptReplaceTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptReplaceTaskResponse) ProtoMessage() {}

func (x *DeptReplaceTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptReplaceTaskResponse.ProtoReflect.Descriptor instead.
func (*DeptReplaceTaskResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{25}
}

func (x *DeptReplaceTaskResponse) GetTasks() *task.TaskSeq {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// SetManagedCores
type DeptSetManagedCoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Department   *Department `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	ManagedCores float32     `protobuf:"fixed32,2,opt,name=managed_cores,json=managedCores,proto3" json:"managed_cores,omitempty"`
}

func (x *DeptSetManagedCoresRequest) Reset() {
	*x = DeptSetManagedCoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptSetManagedCoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptSetManagedCoresRequest) ProtoMessage() {}

func (x *DeptSetManagedCoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptSetManagedCoresRequest.ProtoReflect.Descriptor instead.
func (*DeptSetManagedCoresRequest) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{26}
}

func (x *DeptSetManagedCoresRequest) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

func (x *DeptSetManagedCoresRequest) GetManagedCores() float32 {
	if x != nil {
		return x.ManagedCores
	}
	return 0
}

type DeptSetManagedCoresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeptSetManagedCoresResponse) Reset() {
	*x = DeptSetManagedCoresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OpenCue_proto_department_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptSetManagedCoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptSetManagedCoresResponse) ProtoMessage() {}

func (x *DeptSetManagedCoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OpenCue_proto_department_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptSetManagedCoresResponse.ProtoReflect.Descriptor instead.
func (*DeptSetManagedCoresResponse) Descriptor() ([]byte, []int) {
	return file_OpenCue_proto_department_proto_rawDescGZIP(), []int{27}
}

var File_OpenCue_proto_department_proto protoreflect.FileDescriptor

var file_OpenCue_proto_department_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x75, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x18, 0x4f, 0x70,
	0x65, 0x6e, 0x43, 0x75, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x73, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x70,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x70, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x69, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x69, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x43, 0x6f,
	0x72, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x69, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x64, 0x22, 0x49, 0x0a, 0x0d, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x71, 0x12, 0x38, 0x0a, 0x0b, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x0b, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x2c, 0x0a,
	0x16, 0x44, 0x65, 0x70, 0x74, 0x41, 0x64, 0x64, 0x44, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x44,
	0x65, 0x70, 0x74, 0x41, 0x64, 0x64, 0x44, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7d, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x74, 0x41, 0x64,
	0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0a,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6d, 0x69, 0x6e,
	0x43, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x13, 0x44, 0x65, 0x70, 0x74, 0x41, 0x64, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04,
	0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x61, 0x73,
	0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0xc5, 0x01, 0x0a,
	0x13, 0x44, 0x65, 0x70, 0x74, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x04,
	0x74, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x64, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x41, 0x64, 0x64, 0x54,
	0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x6d, 0x61, 0x70,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x74, 0x6d, 0x61, 0x70, 0x1a, 0x37, 0x0a, 0x09, 0x54,
	0x6d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x3b, 0x0a, 0x14, 0x44, 0x65, 0x70, 0x74, 0x41, 0x64, 0x64, 0x54,
	0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x61,
	0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x71, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x22, 0x4f, 0x0a, 0x15, 0x44, 0x65, 0x70, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x54, 0x61,
	0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x70, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x54,
	0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x59, 0x0a, 0x1f,
	0x44, 0x65, 0x70, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x64, 0x6a,
	0x75, 0x73, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x36, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x22, 0x0a, 0x20, 0x44, 0x65, 0x70, 0x74, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4b, 0x0a, 0x11, 0x44,
	0x65, 0x70, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x36, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x74,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x55,
	0x0a, 0x1b, 0x44, 0x65, 0x70, 0x74, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a,
	0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x1e, 0x0a, 0x1c, 0x44, 0x65, 0x70, 0x74, 0x44, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x1a, 0x44, 0x65, 0x70, 0x74, 0x45, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x69, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x69, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64,
	0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x44, 0x65,
	0x70, 0x74, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x44, 0x65, 0x70,
	0x74, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x1e, 0x44, 0x65,
	0x70, 0x74, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x22, 0x4d, 0x0a, 0x13, 0x44, 0x65, 0x70, 0x74, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x64, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0x3b, 0x0a, 0x14, 0x44, 0x65, 0x70, 0x74, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x74, 0x61, 0x73,
	0x6b, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x71, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x35,
	0x0a, 0x1f, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x20, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xcb, 0x01, 0x0a, 0x16, 0x44, 0x65,
	0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x40, 0x0a, 0x04,
	0x74, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x64, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54,
	0x6d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x74, 0x6d, 0x61, 0x70, 0x1a, 0x37,
	0x0a, 0x09, 0x54, 0x6d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3e, 0x0a, 0x17, 0x44, 0x65, 0x70, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x71,
	0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x79, 0x0a, 0x1a, 0x44, 0x65, 0x70, 0x74, 0x53,
	0x65, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6f, 0x72,
	0x65, 0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x44, 0x65, 0x70, 0x74, 0x53, 0x65, 0x74, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x64, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xd5, 0x09, 0x0a, 0x13, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x11, 0x41, 0x64, 0x64,
	0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22,
	0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x74,
	0x41, 0x64, 0x64, 0x44, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x44, 0x65, 0x70, 0x74, 0x41, 0x64, 0x64, 0x44, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x1e, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x44, 0x65, 0x70, 0x74, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x44, 0x65, 0x70, 0x74, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12,
	0x1f, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70,
	0x74, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65,
	0x70, 0x74, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x53, 0x0a, 0x0a, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x12, 0x21, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65,
	0x70, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x44, 0x65, 0x70, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x71, 0x0a, 0x14, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x54, 0x61, 0x73, 0x6b, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x2b, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70,
	0x74, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x64,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x44, 0x65, 0x70, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x12, 0x27, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x54, 0x69, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65,
	0x70, 0x74, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x0f, 0x45, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x12, 0x26, 0x2e,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x12, 0x29, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2a, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70,
	0x74, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x1f, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x71, 0x0a, 0x14, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x2b, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2c, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70,
	0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a,
	0x0c, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x22, 0x2e,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44,
	0x65, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x4d, 0x61, 0x6e,
	0x67, 0x65, 0x64, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x26, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x53, 0x65, 0x74, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x64, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x27, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65,
	0x70, 0x74, 0x53, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x6f, 0x72, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x0a, 0x24, 0x63, 0x6f, 0x6d,
	0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2e, 0x73, 0x70, 0x63, 0x75,
	0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x50, 0x01, 0x5a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_OpenCue_proto_department_proto_rawDescOnce sync.Once
	file_OpenCue_proto_department_proto_rawDescData = file_OpenCue_proto_department_proto_rawDesc
)

func file_OpenCue_proto_department_proto_rawDescGZIP() []byte {
	file_OpenCue_proto_department_proto_rawDescOnce.Do(func() {
		file_OpenCue_proto_department_proto_rawDescData = protoimpl.X.CompressGZIP(file_OpenCue_proto_department_proto_rawDescData)
	})
	return file_OpenCue_proto_department_proto_rawDescData
}

var file_OpenCue_proto_department_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_OpenCue_proto_department_proto_goTypes = []interface{}{
	(*Department)(nil),                       // 0: department.Department
	(*DepartmentSeq)(nil),                    // 1: department.DepartmentSeq
	(*DeptAddDeptNameRequest)(nil),           // 2: department.DeptAddDeptNameRequest
	(*DeptAddDeptNameResponse)(nil),          // 3: department.DeptAddDeptNameResponse
	(*DeptAddTaskRequest)(nil),               // 4: department.DeptAddTaskRequest
	(*DeptAddTaskResponse)(nil),              // 5: department.DeptAddTaskResponse
	(*DeptAddTasksRequest)(nil),              // 6: department.DeptAddTasksRequest
	(*DeptAddTasksResponse)(nil),             // 7: department.DeptAddTasksResponse
	(*DeptClearTasksRequest)(nil),            // 8: department.DeptClearTasksRequest
	(*DeptClearTasksResponse)(nil),           // 9: department.DeptClearTasksResponse
	(*DeptClearTaskAdjustmentsRequest)(nil),  // 10: department.DeptClearTaskAdjustmentsRequest
	(*DeptClearTaskAdjustmentsResponse)(nil), // 11: department.DeptClearTaskAdjustmentsResponse
	(*DeptDeleteRequest)(nil),                // 12: department.DeptDeleteRequest
	(*DeptDeleteResponse)(nil),               // 13: department.DeptDeleteResponse
	(*DeptDisableTiManagedRequest)(nil),      // 14: department.DeptDisableTiManagedRequest
	(*DeptDisableTiManagedResponse)(nil),     // 15: department.DeptDisableTiManagedResponse
	(*DeptEnableTiManagedRequest)(nil),       // 16: department.DeptEnableTiManagedRequest
	(*DeptEnableTiManagedResponse)(nil),      // 17: department.DeptEnableTiManagedResponse
	(*DeptGetDepartmentNamesRequest)(nil),    // 18: department.DeptGetDepartmentNamesRequest
	(*DeptGetDepartmentNamesResponse)(nil),   // 19: department.DeptGetDepartmentNamesResponse
	(*DeptGetTasksRequest)(nil),              // 20: department.DeptGetTasksRequest
	(*DeptGetTasksResponse)(nil),             // 21: department.DeptGetTasksResponse
	(*DeptRemoveDepartmentNameRequest)(nil),  // 22: department.DeptRemoveDepartmentNameRequest
	(*DeptRemoveDepartmentNameResponse)(nil), // 23: department.DeptRemoveDepartmentNameResponse
	(*DeptReplaceTaskRequest)(nil),           // 24: department.DeptReplaceTaskRequest
	(*DeptReplaceTaskResponse)(nil),          // 25: department.DeptReplaceTaskResponse
	(*DeptSetManagedCoresRequest)(nil),       // 26: department.DeptSetManagedCoresRequest
	(*DeptSetManagedCoresResponse)(nil),      // 27: department.DeptSetManagedCoresResponse
	nil,                                      // 28: department.DeptAddTasksRequest.TmapEntry
	nil,                                      // 29: department.DeptReplaceTaskRequest.TmapEntry
	(*task.Task)(nil),                        // 30: task.Task
	(*task.TaskSeq)(nil),                     // 31: task.TaskSeq
}
var file_OpenCue_proto_department_proto_depIdxs = []int32{
	0,  // 0: department.DepartmentSeq.departments:type_name -> department.Department
	0,  // 1: department.DeptAddTaskRequest.department:type_name -> department.Department
	30, // 2: department.DeptAddTaskResponse.task:type_name -> task.Task
	0,  // 3: department.DeptAddTasksRequest.department:type_name -> department.Department
	28, // 4: department.DeptAddTasksRequest.tmap:type_name -> department.DeptAddTasksRequest.TmapEntry
	31, // 5: department.DeptAddTasksResponse.tasks:type_name -> task.TaskSeq
	0,  // 6: department.DeptClearTasksRequest.department:type_name -> department.Department
	0,  // 7: department.DeptClearTaskAdjustmentsRequest.department:type_name -> department.Department
	0,  // 8: department.DeptDeleteRequest.department:type_name -> department.Department
	0,  // 9: department.DeptDisableTiManagedRequest.department:type_name -> department.Department
	0,  // 10: department.DeptEnableTiManagedRequest.department:type_name -> department.Department
	0,  // 11: department.DeptGetTasksRequest.department:type_name -> department.Department
	31, // 12: department.DeptGetTasksResponse.tasks:type_name -> task.TaskSeq
	0,  // 13: department.DeptReplaceTaskRequest.department:type_name -> department.Department
	29, // 14: department.DeptReplaceTaskRequest.tmap:type_name -> department.DeptReplaceTaskRequest.TmapEntry
	31, // 15: department.DeptReplaceTaskResponse.tasks:type_name -> task.TaskSeq
	0,  // 16: department.DeptSetManagedCoresRequest.department:type_name -> department.Department
	2,  // 17: department.DepartmentInterface.AddDepartmentName:input_type -> department.DeptAddDeptNameRequest
	4,  // 18: department.DepartmentInterface.AddTask:input_type -> department.DeptAddTaskRequest
	6,  // 19: department.DepartmentInterface.AddTasks:input_type -> department.DeptAddTasksRequest
	8,  // 20: department.DepartmentInterface.ClearTasks:input_type -> department.DeptClearTasksRequest
	10, // 21: department.DepartmentInterface.ClearTaskAdjustments:input_type -> department.DeptClearTaskAdjustmentsRequest
	12, // 22: department.DepartmentInterface.Delete:input_type -> department.DeptDeleteRequest
	14, // 23: department.DepartmentInterface.DisableTiManaged:input_type -> department.DeptDisableTiManagedRequest
	16, // 24: department.DepartmentInterface.EnableTiManaged:input_type -> department.DeptEnableTiManagedRequest
	18, // 25: department.DepartmentInterface.GetDepartmentNames:input_type -> department.DeptGetDepartmentNamesRequest
	20, // 26: department.DepartmentInterface.GetTasks:input_type -> department.DeptGetTasksRequest
	22, // 27: department.DepartmentInterface.RemoveDepartmentName:input_type -> department.DeptRemoveDepartmentNameRequest
	24, // 28: department.DepartmentInterface.ReplaceTasks:input_type -> department.DeptReplaceTaskRequest
	26, // 29: department.DepartmentInterface.SetMangedCores:input_type -> department.DeptSetManagedCoresRequest
	3,  // 30: department.DepartmentInterface.AddDepartmentName:output_type -> department.DeptAddDeptNameResponse
	5,  // 31: department.DepartmentInterface.AddTask:output_type -> department.DeptAddTaskResponse
	7,  // 32: department.DepartmentInterface.AddTasks:output_type -> department.DeptAddTasksResponse
	9,  // 33: department.DepartmentInterface.ClearTasks:output_type -> department.DeptClearTasksResponse
	11, // 34: department.DepartmentInterface.ClearTaskAdjustments:output_type -> department.DeptClearTaskAdjustmentsResponse
	13, // 35: department.DepartmentInterface.Delete:output_type -> department.DeptDeleteResponse
	15, // 36: department.DepartmentInterface.DisableTiManaged:output_type -> department.DeptDisableTiManagedResponse
	17, // 37: department.DepartmentInterface.EnableTiManaged:output_type -> department.DeptEnableTiManagedResponse
	19, // 38: department.DepartmentInterface.GetDepartmentNames:output_type -> department.DeptGetDepartmentNamesResponse
	21, // 39: department.DepartmentInterface.GetTasks:output_type -> department.DeptGetTasksResponse
	23, // 40: department.DepartmentInterface.RemoveDepartmentName:output_type -> department.DeptRemoveDepartmentNameResponse
	25, // 41: department.DepartmentInterface.ReplaceTasks:output_type -> department.DeptReplaceTaskResponse
	27, // 42: department.DepartmentInterface.SetMangedCores:output_type -> department.DeptSetManagedCoresResponse
	30, // [30:43] is the sub-list for method output_type
	17, // [17:30] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_OpenCue_proto_department_proto_init() }
func file_OpenCue_proto_department_proto_init() {
	if File_OpenCue_proto_department_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_OpenCue_proto_department_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Department); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepartmentSeq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptAddDeptNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptAddDeptNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptAddTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptAddTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptAddTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptAddTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptClearTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptClearTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptClearTaskAdjustmentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptClearTaskAdjustmentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptDisableTiManagedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptDisableTiManagedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptEnableTiManagedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptEnableTiManagedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptGetDepartmentNamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptGetDepartmentNamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptGetTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptGetTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptRemoveDepartmentNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptRemoveDepartmentNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptReplaceTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptReplaceTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptSetManagedCoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OpenCue_proto_department_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptSetManagedCoresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_OpenCue_proto_department_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_OpenCue_proto_department_proto_goTypes,
		DependencyIndexes: file_OpenCue_proto_department_proto_depIdxs,
		MessageInfos:      file_OpenCue_proto_department_proto_msgTypes,
	}.Build()
	File_OpenCue_proto_department_proto = out.File
	file_OpenCue_proto_department_proto_rawDesc = nil
	file_OpenCue_proto_department_proto_goTypes = nil
	file_OpenCue_proto_department_proto_depIdxs = nil
}
